### ISSUE TITLE
please delete  "mqMorphoDigCore::"

### ISSUE THREAD

**Issue by wwp20022005** [morphomuseum/MorphoDig#13]
https://github.com/morphomuseum/MorphoDig/blob/a62e5459b9cead97086951e0db4928f1197e9418/MorphoDig/Qt/mqMorphoDigCore.h#L917

**Comment by wwp20022005** [comment]
delete "mqMorphoDigCore::"

**Comment by renaud-lebrun** [comment]
Thanks you. I fixed it.
